apiVersion: apps/v1
kind: Deployment
metadata:
  name: es-hq
  labels:
    component: elasticsearch
    role: hq
spec:
  replicas: 1
  selector:
    matchLabels:
      component: elasticsearch
      role: hq
  template:
    metadata:
      labels:
        component: elasticsearch
        role: hq
    spec:
      containers:
        - name: es-hq
          image: elastichq/elasticsearch-hq:release-v3.5.4
          env:
            - name: HQ_DEFAULT_URL
              value: http://elasticsearch:9200
          resources:
            limits:
              cpu: 0.2
            requests:
              cpu: 0.1
          ports:
            - containerPort: 5000
              name: http
---
apiVersion: v1
kind: Service
metadata:
  name: es-hq
  labels:
    component: elasticsearch
    role: hq
spec:
  selector:
    component: elasticsearch
    role: hq
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  type: LoadBalancer