---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
  name: "docker-in-docker"
  labels:
    app: "docker-in-docker"
    tier: "backend"
data:
  DOCKER_TLS_CERTDIR: ""
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "docker-in-docker"
  labels:
    app: "docker-in-docker"
    tier: "backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "docker-in-docker"
      tier: "backend"
  template:
    metadata:
      labels:
        app: "docker-in-docker"
        tier: "backend"
    spec:
      containers:
        - image: "docker:dind"
          name: "docker-in-docker"
          securityContext:
            privileged: true
          ports:
            - containerPort: 2375
              protocol: "TCP"
          envFrom:
            - configMapRef:
                name: "docker-in-docker"
---
apiVersion: "v1"
kind: "Service"
metadata:
  name: "docker-in-docker"
  labels:
    app: "docker-in-docker"
    tier: "backend"
spec:
  ports:
    - name: "docker"
      port: 2375
      protocol: "TCP"
  selector:
    app: "docker-in-docker"
    tier: "backend"
  type: "ClusterIP"
